### ISSUE TITLE
MonkeyTiger

### ISSUE THREAD

**Issue by MonkeyTiger** [selimerunkut/pixelk_c4_nft_frontend#3]
Have you skype? Please invite me

live:.cid.4b5e66611cb51690

**Comment by selimerunkut** [comment]
@MonkeyTiger can not find your skype, if you have telegram please find my handle https://t.me/selimerunkut

**Comment by MonkeyTiger** [comment]
Don't you have a skype?

**Comment by selimerunkut** [comment]
@MonkeyTiger https://join.skype.com/invite/dpcwLHM8zvmj 
mostly not online on skype; I'm using Telegram
